### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by rrjanbiah** [rrjanbiah/react2solid#4]
When trying to integrate the monaco editor, again getting Buffer related error (but different stack error):

```
Uncaught ReferenceError: Buffer is not defined
    at node_modules/jsesc/jsesc.js (jsesc.js:33:18)
    at __require (chunk-FFUGYK5D.js?v=67085410:11:50)
    at node_modules/@babel/generator/lib/generators/types.js (types.js:29:14)
    at __require (chunk-FFUGYK5D.js?v=67085410:11:50)
    at node_modules/@babel/generator/lib/generators/index.js (index.js:85:14)
    at __require (chunk-FFUGYK5D.js?v=67085410:11:50)
    at node_modules/@babel/generator/lib/printer.js (printer.js:14:26)
    at __require (chunk-FFUGYK5D.js?v=67085410:11:50)
    at node_modules/@babel/generator/lib/index.js (index.js:11:16)
    at __require (chunk-FFUGYK5D.js?v=67085410:11:50)
```

**Comment by rrjanbiah** [comment]
After scratching my head for a while on this, it turned out to be that I chose the wrong SolidJS template. (I wrongly chose `solidjs/templates/ts-windicss` instead of `solidjs/templates/ts-tailwindcss` which I'm familiar with in terms of PoCs). So, had to switch to `solidjs/templates/ts-tailwindcss` by overwriting and adjusting files. Although not much noticeable changes, it did fix the error.

**Comment by rrjanbiah** [comment]
Weird. Again the same error and stack when trying to add `jq-web`:

```
Uncaught ReferenceError: Buffer is not defined
    at node_modules/jsesc/jsesc.js (jsesc.js:33:18)
    at __require (chunk-RJRH6FXO.js?v=4f075eb8:11:50)
    at node_modules/@babel/generator/lib/generators/types.js (types.js:29:14)
    at __require (chunk-RJRH6FXO.js?v=4f075eb8:11:50)
    at node_modules/@babel/generator/lib/generators/index.js (index.js:85:14)
    at __require (chunk-RJRH6FXO.js?v=4f075eb8:11:50)
    at node_modules/@babel/generator/lib/printer.js (printer.js:14:26)
    at __require (chunk-RJRH6FXO.js?v=4f075eb8:11:50)
    at node_modules/@babel/generator/lib/index.js (index.js:11:16)
    at __require (chunk-RJRH6FXO.js?v=4f075eb8:11:50)
```

**Comment by rrjanbiah** [comment]
Again, weird that adding `@esbuild-plugins/node-modules-polyfill` as dev dependency, fixed the error once. But, when I tried to uninstall it for `git push` and reinstalled the same didn't work.

**Comment by rrjanbiah** [comment]
Though https://stackoverflow.com/a/70719923/10218987 seems to have helped, this issue is strange as in the https://github.com/rrjanbiah/react2solid/commit/a61209307bcce1ae263eebbb3f0728611e75049a

```js
buffer: true,
```
in https://github.com/rrjanbiah/react2solid/commit/a61209307bcce1ae263eebbb3f0728611e75049a#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR16 is rarely helpful. Sometimes, even by commenting out it works.. meaning, adding `@esbuild-plugins/node-modules-polyfill` merely as a dev dependency still works randomly.
